In [1]:
# Lets first discuss some useful array attributes
# Lets create a 1D, 2D, and 3D array filled with random numbers which will aslo be seeded
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3, 4, 5))

# Each aray has ndim (# of dimensions), shape (size of dimension), and size (size of array)

print("x3 dim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 dim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [2]:
# We can also find out the data type
print("dtype: ", x3.dtype)

dtype:  int32


In [3]:
# itemsize and nbytes lists the size (in bytes) of each array element and total size of the array
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes


In [4]:
# In 1D arrays, we can access the i'th value by specifying desired index in sqaure brackets
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
# To index from the end, use negative indicies
x1[-1]

9

In [9]:
x1[-2]

7

In [10]:
# For Multi-D arrays, we acces items using comma-seperated tuple of indicies
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

1

In [13]:
x2[2, -1]

7

In [15]:
# We can also modify any of the elements in the array
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
# Note: NumPy arrays have a fixed data type so if you insert a floating-point value into an integer array, that value will be truncated
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])