In [1]:
# This is an introduction to the Numpy Module
# First lets start by importing NumPy and checking  its version
import numpy
numpy.__version__

'1.15.4'

In [2]:
# Most people in the SciPy/PyData community import NumPy using np as an alias so we will too
import numpy as np

In [4]:
# Lets describe how a List is more than just a List in python
# Lets create a list of integers first
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [6]:
# Now a list of strings
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
# We can mix up our types in a list as well
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
# Important to note that all this flexibility comes at a cost
# Each item in list contains type info, reference count, etc.
# In other words, each item is a complete Python object

In [9]:
# Lets use arrays
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# We first created a list, then turned it into an array with 'i' as the encoding for this array of integers

In [10]:
# Now lets create a NumPy integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [11]:
# Note: unlike lists, NumPy is constrained to arrays that all contain the same type
# If types do not match, NumPy will upcast like below's output
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
# We can explicitly set the data type of the array like below
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
# Unlike Python Lists, NumPy arrays can be explicitly multidimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# For larger arrays, more efficient to create arrays from scratch
# Ex. Create an array of length 10 filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Ex. Create 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Ex. Create 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])